version: "3.8"
services:
  db:
    restart: always
    image: postgres:12.3
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "passwsss*1348394#"
      POSTGRES_DB: "edgy"
    expose:
      - "5432"
    volumes:
        - "edgy:/data/db"
    command: >-
        --jit=false
    ports:
      - "5432:5432"

  edgy_alt:
    restart: always
    image: postgres:12.3
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "edgy_alt"
    volumes:
        - "edgy_alt:/data/db"
    command: >-
        --jit=false
    ports:
      - "5433:5432"


volumes:
  edgy:
    external: true
  edgy_alt:
      external: true
