import edgy
from edgy.contrib.contenttypes import ContentTypeField

database = edgy.Database("sqlite:///db.sqlite")
models = edgy.Registry(database=database, with_content_type=True)


class PersonsOrganisations(edgy.Model):
    content_type = ContentTypeField()
    # to and from fields will be autogenerated

    class Meta:
        abstract = True


class Person(edgy.Model):
    first_name = edgy.fields.CharField(max_length=100)
    last_name = edgy.fields.CharField(max_length=100)

    class Meta:
        registry = models
        unique_together = [("first_name", "last_name")]


class Organisation(edgy.Model):
    name = edgy.fields.CharField(max_length=100, unique=True)
    persons = edgy.fields.ManyToMany(to=Person, through=PersonsOrganisations)

    class Meta:
        registry = models
