#!/bin/sh -e

if [ ! -z "$GITHUB_ACTIONS" ]; then
  if [ -z "$VERSION_FILE" ]; then
    echo "VERSION_FILE is missing"
    exit 1
  fi
  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
  git config --local user.name "GitHub Action"

  VERSION=`grep __version__ ${VERSION_FILE} | grep -o '[0-9][^"]*'`

  if [ "refs/tags/${VERSION}" != "${GITHUB_REF}" ] ; then
    echo "GitHub Ref '${GITHUB_REF}' did not match package version '${VERSION}'"
    exit 1
  fi
fi

set -x

hatch upload dist/*
